Lot<-read.csv(file="WiscLottery.csv", header = TRUE)
summary(Lot$POP)
summary(Lot$SALES)
par(mfrow = c(1,2))
hist(Lot$POP, main = "Histogram of Population", xlab = "population", ylab = "Counts")
hist(Lot$SALES, main = "Histogram of Sales", xlab = "sales", ylab = "Counts")
plot(Lot$POP, Lot$SALES, xlab = "population", ylab = "sales", main = "Scatter Plot of Population and Sales", pch = 20)
cor(Lot$POP, Lot$SALES)
model_blr <- lm(SALES ~ POP, data = Lot)
plot(Lot$POP, Lot$SALES, xlab = "population", ylab = "sales", main = "Scatter Plot of Population and Sales", pch = 20)
abline(model_blr, col = "blue")
abline(0,1, col = "red")
summary(model_blr)
anova(model_blr)
summary(model_blr)$coefficients
#confidence interval
confint(model_blr, level = .90)
confint(model_blr, levle = .95)
#prediction interval
NewData <- data.frame(POP = 10000)
predict(model_blr, NewData, interval = "prediction", level = .90)
NewData <- data.frame(POP = c(10000, 20000))
predict(model_blr, NewData, interval = "prediction", level = .99)
min(Lot$POP)
max(Lot$POP)
new.pop <- seq(min(Lot$POP), max(Lot$POP), length.out = 200)
NewData <- data.frame(POP = new.pop)
pred.int <- predict(model_blr, NewData, interval = "prediction", level = .99)
plot(new.pop, pred.int[, "fit"], type = 'l')
lines(new.pop, pred.int[, "lwr"], type = 'l')
lines(new.pop, pred.int[, "upr"], type = 'l')
#residual analysis
plot(Lot$POP, model_blr$residuals, xlab = "POP", ylab = "Residual")
