Term <- read.csv("TermLife.csv", header = TRUE)
names(Term)
dim(Term)
Term[1:20,]
Term$FACEPOS = 1*(Term$FACE>0)
table(Term$FACEPOS)
means_table <- aggregate(. ~ Term$FACEPOS, data = Term, FUN = mean)
print(means_table)
Term$LNINCOME <- log(Term$INCOME)
lpm_model <- lm(FACEPOS ~ LNINCOME + EDUCATION + AGE + GENDER + MARSTAT, data = Term)
summary(lpm_model)
coef(lpm_model)
PosExpglm = glm(FACEPOS ~ LNINCOME + EDUCATION + AGE + GENDER + MARSTAT, binomial(link=logit), data = Term)
summary(PosExpglm)
conf_intervals <- confint(PosExpglm, level = 0.95)
print(conf_intervals)
Term$MARSTAT1 = 1*(Term$MARSTAT>0)
table(Term$MARSTAT1)
MarStatglm = glm(FACEPOS ~ LNINCOME + EDUCATION + MARSTAT1, binomial(link=logit), data = Term)
summary(MarStatglm)
LRT<-2*(logLik(MarStatglm)-logLik(PosExpglm))
print(LRT)
coef(MarStatglm)
