Lot<-read.csv(file="WiscLottery.csv", header = TRUE)
summary(Lot$PERPERHH)
summary(Lot$MEDSCHYR)
summary(Lot$MEDHVL)
summary(Lot$PRCRENT)
summary(Lot$PRC55P)
summary(Lot$HHMEDAGE)
summary(Lot$MEDINC)
summary(Lot$SALES)
summary(Lot$POP)
sd(Lot$MEDSCHYR)
sd(Lot$MEDHVL)
cor(Lot$PERPERHH, Lot$SALES)
cor(Lot$MEDSCHYR, Lot$SALES)
cor(Lot$MEDHVL, Lot$SALES)
cor(Lot$PRCRENT, Lot$SALES)
cor(Lot$PRC55P, Lot$SALES)
cor(Lot$HHMEDAGE, Lot$SALES)
cor(Lot$MEDINC, Lot$SALES)
cor(Lot$POP, Lot$SALES)
Term5 <- Lot[c("PERPERHH", "MEDSCHYR", "MEDHVL", "PRCRENT", "PRC55P", "HHMEDAGE", "MEDINC", "POP", "SALES")]
pairs(Term5, upper.panel = NULL, gap = 0, cex.labels = 1.25, pch =20)
model_perperhh <- lm(SALES ~ PERPERHH, data = Lot)
summary(model_perperhh)
plot(Lot$PERPERHH, Lot$SALES, xlab = "PERPERHH", ylab = "SALES")
abline(model_perperhh, col ="red")
model_medschyr <- lm(SALES ~ MEDSCHYR, data = Lot)
summary(model_medschyr)
plot(Lot$MEDSCHYR, Lot$SALES, xlab = "MEDSCHYR", ylab = "SALES")
abline(model_medschyr, col ="red")
model_medhvl <- lm(SALES ~ MEDHVL, data = Lot)
summary(model_medhvl)
plot(Lot$MEDHVL, Lot$SALES, xlab = "MEDHVL", ylab = "SALES")
abline(model_medhvl, col ="red")
model_prcrent <- lm(SALES ~ PRCRENT, data = Lot)
summary(model_prcrent)
plot(Lot$PRCRENT, Lot$SALES, xlab = "PRCRENT", ylab = "SALES")
abline(model_prcrent, col ="red")
model_prc55p <- lm(SALES ~ PRC55P, data = Lot)
summary(model_prc55p)
plot(Lot$PRC55P, Lot$SALES, xlab = "PRC55P", ylab = "SALES")
abline(model_prc55p, col ="red")
model_hhmedage <- lm(SALES ~ HHMEDAGE, data = Lot)
summary(model_hhmedage)
plot(Lot$HHMEDAGE, Lot$SALES, xlab = "HHMEDAGE", ylab = "SALES")
abline(model_hhmedage, col ="red")
model_medinc <- lm(SALES ~ MEDINC, data = Lot)
summary(model_medinc)
plot(Lot$MEDINC, Lot$SALES, xlab = "MEDINC", ylab = "SALES")
abline(model_medinc, col ="red")
model_pop <- lm(SALES ~ POP, data = Lot)
summary(model_pop)
plot(Lot$POP, Lot$SALES, xlab = "POP", ylab = "SALES")
abline(model_pop, col ="red")
model_multiple <- lm(SALES ~ MEDSCHYR + MEDHVL + POP, data = Lot)
summary(model_multiple)
residuals <- residuals(model_multiple)
model_multiple_medschyr <- lm(SALES ~ MEDHVL + POP, data = Lot)
residuals_medschyr <- residuals(model_multiple_medschyr)
partial_corr_multiple <- cor(residuals, residuals_medschyr)
print(partial_corr_multiple)
plot(residuals, residuals_medschyr)
model_multiple_11 <- lm(SALES ~ MEDSCHYR + MEDHVL + POP, data = Lot, subset = -c(11))
summary(model_multiple_11)
model_multiple_9 <- lm(SALES ~ MEDSCHYR + MEDHVL + POP, data = Lot, subset = -c(9))
summary(model_multiple_9)
